name: Sync labels

on:
  workflow_dispatch:

jobs:
  # ref: https://github.com/shinGangan/.github/blob/main/.github/workflows/sync-labels.yml
  sync-labels:
    uses: shinGangan/.github/.github/workflows/sync-labels.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
